### ISSUE TITLE
The quickstart guide is out of date

### ISSUE THREAD

**Issue by Masterchef365** [unit8co/vegans#34]
Seems as though data loaders aren't actually provided since I get `module 'vegans.utils.loading' has no attribute 'MNISTLoader'` when I try to run the example script

**Comment by tneuer** [comment]
Hello @Masterchef365. Thanks for bringing this to our attention. I think the problem is that the Quickstart is unfortunately ahead and show cases the actual use while our master branch is out of date. We will do some tests but the problem should be solved for now by using our develop branch.
We will test this, merge the develop branch and make a new release as soon as possible!

**Comment by tneuer** [comment]
It took a while and I had so resolve some minor issues but the quickstart guide should now be up-to-date and in sync with the new vegans version 0.4.0.
I'll keep this issue open for a week or two to see if someone spots similar issues. Otherwise I'll consider it closed :)
